language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

licenses:
  - '.+'

before_script:
  - cp mock-google-services.json app/google-services.json
  - cp mock-secret.xml app/src/main/res/values/secret.xml